### ISSUE TITLE
Great job with this

### ISSUE THREAD

**Issue by MrLeebo** [indeedeng/react-singleton-context#8]
This package worked perfectly on the first try, which is a rare treat when dealing with module federation configs! I don't actually have an issue, I just wanted to offer some encouragement 👏

**Comment by tcschiller** [comment]
What a lovely note. Thanks so very much! I'm glad this worked out for you.

**Comment by harishmathur** [comment]
@MrLeebo - Could you please provide a full usage example/reference i.e. configs on both host and child app

**Comment by MrLeebo** [comment]
Not exactly. The repo in question is closed source, and if I tried to copy all of the code relevant to the explanation, it would stretch out to several pages long.

Suffice to say that it's an example like what's described in the README. A Micro Front-End application with a host that shares a `<Shell />` component (which renders the general layout elements and the client router) and several utility components.

Then, there are remote apps that federate the implementations for specific pages and make use of the shared utilities from the host so that each remote looks and feels like an indistinguishable part of the host app, and not some tacked-on `<iframe>` window.

The `<Shell />` host component renders the client router and imports components from the remotes when it renders the page that the remote is responsible for.

One of the contexts that the host renders is a `<BreadcrumbContextProvider>`, which is used to render a `<BreadcrumbList>` component of the pages the user has recently visited. The page can render a Breadcrumb to add an entry to the Breadcrumb list, and they can click on it to go back to that page.

```ts
<Breadcrumb>Project Summary</Breadcrumb>
```

The Breadcrumb component is exposed by the host's federated config. The Breadcrumb context needs to be a singleton so that the host app and remote app can access the same context values.

This is the case for any Context Provider that gets rendered in `<Shell />`, which the remotes may need to access.

**Comment by MrLeebo** [comment]
@harishmathur here's a [gist with simplified versions of both configs](https://gist.github.com/MrLeebo/0304eb988c71d5be8e395f6df3a12be4)

**Comment by harishmathur** [comment]
Thanks a lot for sharing the configs. Really appreciate. Just last few things from your configs ;
1. Is the shared 'react-singleton-context' specified only in the host config ?
2. Is Breadcrumb your context object in this case ?
3. It would really help if you can show how you are actually using the registered (i.e via createRegisteredContext) in other module.

For my use case, I would have a Context API object set in the host module and I want to just access/read the same in another child app. So assume this use case would be similar to what you have here.

**Comment by MrLeebo** [comment]
1. `react-singleton-context` is only ever imported by the host. The child never has cause to have it as a dependency. Perhaps in the future there could be a remote that shares components with the host bidirectionally and those components will depend on a singleton context that the remote declares, but at this time we don't have anything like that.
2. It is a react component that consumes the context object. The context provider gets rendered by `<Shell />` along with any other contexts the application needs for data or functionality
3. Not any different than how it appears in the README

```ts
const FooContext = createRegisteredContext<Foo>(
  "FooContext",
  null
);

export const useFooContext = () => useContext(FooContext);

<FooContext.Provider value={...}>
  {children}
</FooContext.Provider>
```

**Comment by harishmathur** [comment]
Thanks again for the details.  I am not sure if for the below line, you actually meant getContext(FooContext)

`export const useFooContext = () => useContext(FooContext);`

I was trying to implement/use this react-singleton-context library first in a standalone React app (without any Module Federation), but have been getting some errors (including object is not iterable)
Below is the codesandbox link;
https://codesandbox.io/p/sandbox/shared-context-r4f4tw

Could you please have a look and see if there is some issue in how this is implemented.

**Comment by harishmathur** [comment]
I have updated the codesandbox and am able to read the context (registered via createRegisteredContext) in a child component
https://codesandbox.io/p/sandbox/shared-context-r4f4tw

It would be really helpful if you could have a quick glance at this standalone codesandbox to see if my setup is good.

**Comment by harishmathur** [comment]
If codesandbox looks correct, I am trying to implement the same in my Module Federation app. But I am seeing below error

```
Error: Module "./SharedDataContext" does not exist in container.
while loading "./SharedDataContext" from webpack/container/reference/host
```

For my host config, I have 
```
exposes: {
    "/SharedDataContext" : "./src/sharedDataContext.js" // This is exactly the same as the context object I have shown in codesandbox link
  },
shared: {
    ...dependencies,
    'react-singleton-context': {
      singleton: true,
      eager: true
    }
  }
```

and for my remote config, I have 
```
remotes: {
      host: "host@http://localhost:3000/remoteEntry.js"
    },
```

and in the remote module, I am importing  as below;

`import {getSharedDataContext} from 'host/SharedDataContext';
`
and then trying to read the context as below
`const [sharedData] = React.useContext(getSharedDataContext());`


Not sure if I am missing something in the config.

**Comment by MrLeebo** [comment]
"/SharedDataContext" should be "./SharedDataContext" in "exposes"

**Comment by harishmathur** [comment]
Oh Wow !! It seems to be working finally (after changing to "/SharedDataContext" to "./SharedDataContext ) and I am now able to access/read the same shared context which I set in the host module...

I assume the way I have defined sharedDataContext.js (above) with createRegisteredContext/getContext and the relevant configurations I have shown related to Module Federation looks good.

Really appreciate your help in fixing the issues I encountered.

**Comment by MrLeebo** [comment]
I think you should be using the `useContext` hook. I think `getContext` is intended more for meta library stuff, and not regular application usage. I would expect that if you use `getContext` you're always going to get the default value of the context, not the value determined by the nearest Provider.

**Comment by harishmathur** [comment]
That is so cool...
In the remote modules, I have now replaced getContext with useContext and am importing the SharedDataContext from host as below;

`import {SharedDataContext} from 'host/SharedDataContext';
`

The other thing is it also makes it a seamless change for the child/remote modules who'll continue to useContext() like they would do in a non-Module Federated app instead of having to do 
`React.useContext(getSharedDataContext())`

I somehow now realize why in the Readme/documentation, it only talks about createRegisteredContext and nothing about getContext()

**Comment by harishmathur** [comment]
Assume I have a near perfect implementation now...
sharedDataContext.js setup - Providing and Consuming values
Configurations - Both host and child modules

Thanks again !

**Comment by harishmathur** [comment]
@MrLeebo - With this library, if there is any update to the context residing in the host, can the child application get to know the updated context value ?

**Comment by MrLeebo** [comment]
Yeah. It behaves the same as any other context from your react app's perspective.
